## Basic Array Arithmetic

In [1]:
# Run this cell to set up the notebook, but please don't change it.

# These lines import the Numpy and Datascience modules.
import numpy as np
from datascience import *

# These lines do some fancy plotting magic
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import warnings
warnings.simplefilter('ignore', FutureWarning)

# These lines load the tests.
from client.api.assignment import load_assignment 
tests = load_assignment('basic_array_arithmetic.ok')

WARNING  | guidance.py:102 | Failed to read .ok_guidance file. It may not exist


Assignment: Basic Array Arithmetic
OK, version v1.12.10



**Question 1.** Multiply the numbers 42, 4224, 42422424, and -250 by 157.  For this question, **don't** use arrays.

In [2]:
first_product = 42 * 157
second_product = 4224* 157
third_product = 42422424 * 157
fourth_product = -250 * 157
print(first_product, second_product, third_product, fourth_product)

6594 663168 6660320568 -39250


In [3]:
_ = tests.grade('q1')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 2.** Now, do the same calculation, but using an array and only a single multiplication (`*`) operator.  Put the 4 results in an array named `products`.

In [34]:
# You may find it useful to first define an array called
# numbers, but you don't have to.
numbers = np.array([42, 4224, 42422424, -250], dtype=np.int64)
products = 157 * numbers
products

array([      6594,     663168, 6660320568,     -39250], dtype=int64)

In [32]:
type(third_product)

int

In [23]:
_ = tests.grade('q2')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
 > Suite 1 > Case 1

>>> products
array([      6594,     663168, 6660320568,     -39250], dtype=int64)

# Error: expected
#     array([      6594,     663168, 6660320568,     -39250])
# but got
#     array([      6594,     663168, 6660320568,     -39250], dtype=int64)

Run only this test case with "python3 ok -q q2 --suite 1 --case 1"
---------------------------------------------------------------------
Test summary
    Passed: 0
    Failed: 1
[k..........] 0.0% passed



**Question 3.** Oops, we made a typo!  Instead of 157, we wanted to multiply each number by 1577.  Compute the fixed products in the cell below using array arithmetic.  Notice that your job is really easy if you previously defined an array containing the 4 numbers.

In [35]:
fixed_products = numbers * 1577
fixed_products

array([      66234,     6661248, 66900162648,     -394250], dtype=int64)

In [36]:
_ = tests.grade('q3')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
 > Suite 1 > Case 1

>>> fixed_products
array([      66234,     6661248, 66900162648,     -394250], dtype=int64)

# Error: expected
#     array([      66234,     6661248, 66900162648,     -394250])
# but got
#     array([      66234,     6661248, 66900162648,     -394250], dtype=int64)

Run only this test case with "python3 ok -q q3 --suite 1 --case 1"
---------------------------------------------------------------------
Test summary
    Passed: 0
    Failed: 1
[k..........] 0.0% passed



**Question 4.** We've loaded an array of temperatures in the next cell.  Each number is the highest temperature observed on a day at a climate observation station, mostly from the US.  Since they're from the US government agency [NOAA](noaa.gov), all the temperatures are in Fahrenheit.  Convert them all to Celsius by first subtracting 32 from them, then multiplying the results by $\frac{5}{9}$.

In [40]:
max_temperatures = Table.read_table("temperatures.csv").column("Daily Max Temperature")

celsius_max_temperatures = (max_temperatures - 32) * (5/9)
celsius_max_temperatures

array([ -3.88888889,  30.55555556,  31.66666667, ...,  16.66666667,
        22.77777778,  16.11111111])

In [41]:
_ = tests.grade('q4')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



**Question 5.** The cell below loads all the *lowest* temperatures from each day (in Fahrenheit).  Compute the size of the daily temperature range for each day.  That is, compute the difference between each daily maximum temperature and the corresponding daily minimum temperature.  **Give your answer in Celsius!**

In [42]:
min_temperatures = Table.read_table("temperatures.csv").column("Daily Min Temperature")

# You may find it useful to first define an array named
# celsius_min_temperatures, but you don't have to do that.
celsius_min_temperatures = (min_temperatures - 32)*(5/9)
celsius_temperature_ranges = abs(celsius_max_temperatures - celsius_min_temperatures)
celsius_temperature_ranges

array([  6.66666667,  10.        ,  12.22222222, ...,  17.22222222,
        11.66666667,  11.11111111])

In [43]:
_ = tests.grade('q5')

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    Passed: 1
    Failed: 0
[ooooooooook] 100.0% passed



In [ ]:
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [tests.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]

In [ ]:
# Run this cell to submit your work *after* you have passed all of the test cells.
# It's ok to run this cell multiple times. Only your final submission will be scored.

!TZ=America/Los_Angeles ipython nbconvert --output=".basic_array_arithmetic_$(date +%m%d_%H%M)_submission.html" basic_array_arithmetic.ipynb